
services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./dataPostgresql:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54321:5432"
    networks:
      - meu-banco

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./dataPgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - meu-banco

  app-banco:
    build:
      context: ../AppBanco
      dockerfile: Dockerfile
    container_name: app-banco
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - meu-banco

networks:
  meu-banco:
    driver: bridge
